// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJygBFjVkDW_f5E7Frmt_g9Qg26C7NQtk',
    appId: '1:763828981244:web:f47560e4de093463f5f679',
    messagingSenderId: '763828981244',
    projectId: 'free-indeed-app',
    authDomain: 'free-indeed-app.firebaseapp.com',
    storageBucket: 'free-indeed-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZYXayRooRfRGQ8ZSmIHh9HaApwO0GkI',
    appId: '1:763828981244:android:0d84e08de215c72bf5f679',
    messagingSenderId: '763828981244',
    projectId: 'free-indeed-app',
    storageBucket: 'free-indeed-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCotO2u9pQx9oPD6M2kJJJag3NPY1Xmx3Q',
    appId: '1:763828981244:ios:6efef72eb231ee96f5f679',
    messagingSenderId: '763828981244',
    projectId: 'free-indeed-app',
    storageBucket: 'free-indeed-app.firebasestorage.app',
    iosBundleId: 'com.example.freeIndeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCotO2u9pQx9oPD6M2kJJJag3NPY1Xmx3Q',
    appId: '1:763828981244:ios:6efef72eb231ee96f5f679',
    messagingSenderId: '763828981244',
    projectId: 'free-indeed-app',
    storageBucket: 'free-indeed-app.firebasestorage.app',
    iosBundleId: 'com.example.freeIndeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJygBFjVkDW_f5E7Frmt_g9Qg26C7NQtk',
    appId: '1:763828981244:web:a14708d851b1f0c0f5f679',
    messagingSenderId: '763828981244',
    projectId: 'free-indeed-app',
    authDomain: 'free-indeed-app.firebaseapp.com',
    storageBucket: 'free-indeed-app.firebasestorage.app',
  );
}
